name: Holosign
main: com.aerilym.holosign.HolosignCore
author: Aerilym
description: Create holographic signs using invisible armor stands with simple commands.
version: 1.0.0
api-version: 1.18
commands:
   holosign:
      description: Use the holosign plugin to create armor stand based signs
      usage: /<command>
      aliases: [hsign, hologram, holo, hs]
      permission: ftscore.holosign